# Generated by Django 4.2.7 on 2025-06-26 08:58

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Asset name (minimum 2 characters)', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('description', models.TextField(blank=True, help_text='Asset description')),
                ('service_time', models.DateTimeField(help_text='When maintenance/service is due')),
                ('expiration_time', models.DateTimeField(help_text='When the asset is no longer valid')),
                ('is_serviced', models.BooleanField(default=False, help_text='Whether the asset has been serviced')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Violation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('violation_type', models.CharField(choices=[('expired_not_serviced', 'Expired and Not Serviced'), ('service_overdue', 'Service Overdue')], max_length=20)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved', models.BooleanField(default=False)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='violations', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('service_reminder', 'Service Reminder'), ('expiration_reminder', 'Expiration Reminder')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_sent', models.BooleanField(default=False)),
                ('asset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='assets.asset')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['service_time'], name='assets_asse_service_b4de85_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['expiration_time'], name='assets_asse_expirat_b6f2e1_idx'),
        ),
        migrations.AddIndex(
            model_name='asset',
            index=models.Index(fields=['is_serviced'], name='assets_asse_is_serv_bff198_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['asset', 'violation_type'], name='assets_viol_asset_i_b8149a_idx'),
        ),
        migrations.AddIndex(
            model_name='violation',
            index=models.Index(fields=['resolved'], name='assets_viol_resolve_3cc0a3_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['asset', 'notification_type'], name='assets_noti_asset_i_2ccda1_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='assets_noti_created_e5128a_idx'),
        ),
    ]
